name: Python Docker Build
on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Extract short commit hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - name: Build docker image
        run: docker buildx build --file ./src/Dockerfile --platform linux/amd64 -t ghcr.io/echoblag/epsessions:${{ env.COMMIT_HASH }}
